//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ESFEA2D.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_SEJIKATYPE                  129
#define IDD_PANEL_MANIP                 129
#define IDS_FILENAME                    129
#define IDC_FINGER                      130
#define IDI_ICON1                       130
#define IDS_MODE                        130
#define IDB_LITTLE_TRIANGLE             131
#define IDI_SEJIKA                      131
#define IDC_SCALE                       132
#define IDB_DONUT                       133
#define IDB_BITMAP_ROTATE               134
#define IDB_IL_TAB                      135
#define IDB_BITMAP_SCALE                136
#define IDB_OUTLINE                     137
#define IDB_BITMAP_MOVE                 138
#define IDD_PANEL_TREE                  138
#define IDR_CAMERA_MENU                 139
#define IDB_TREE_LIST                   139
#define IDD_MATRIX                      141
#define IDD_PANEL_SWITCH                145
#define IDD_PANEL_MESH                  146
#define IDD_PANEL_POINTS                147
#define IDD_PANEL_ANIMATE               148
#define IDD_PANEL_SHAPE                 150
#define IDB_TL_OFF                      150
#define IDD_PANEL_LIGHTS                151
#define IDD_PANEL_OBJECT                152
#define IDB_SELECT_MESH                 152
#define IDB_SELECT_OBJECT               153
#define IDD_PANEL_NUM                   153
#define IDB_SELECT_POINT                154
#define IDB_SELECT_FACE                 155
#define IDP_NODES                       155
#define IDB_FIX                         156
#define IDP_SEL_ND                      156
#define IDP_LOAD                        157
#define IDB_MOVE_LOADS                  158
#define IDP_ANIMATE                     158
#define IDP_MODAL                       159
#define IDB_BITMAP_PERSP                160
#define IDP_ELEMENTS                    160
#define IDB_MODE_COLOR                  161
#define IDB_BITMAP_LIGHT                163
#define IDB_LONG_GREEN                  166
#define IDB_FIX1                        167
#define IDB_LONG_GREEN1                 168
#define IDB_LONG_YELLOW                 169
#define IDB_LONG_RED                    170
#define IDC_SLIDER_DAMPING              1000
#define IDC_SLIDER_MASS                 1001
#define IDC_SLIDER_LOADS                1002
#define IDC_ROTATE                      1003
#define IDC_BREAK_PARAMETERS            1003
#define IDC_MOVE                        1004
#define IDC_BREAK_MASS                  1004
#define IDC_BUTTON_ROTATE               1005
#define IDC_BREAK_DAMPING               1005
#define IDC_BREAK_AMBIENT               1005
#define IDC_BUTTON_MOVE                 1006
#define IDC_BREAK_LOADS                 1006
#define IDC_BREAK_DIRECTION             1006
#define IDC_TREE                        1006
#define IDC_BUTTON_SET_IN_CAM           1007
#define IDC_BREAK_POINT                 1007
#define IDC_BUTTON_SCALE                1008
#define IDC_NUM_1                       1009
#define IDE_X                           1009
#define IDC_NUM_2                       1010
#define IDE_Y                           1010
#define IDC_NUM_3                       1011
#define IDE_DX                          1011
#define IDC_EDIT4                       1012
#define IDE_DY                          1012
#define IDE_FRAC                        1012
#define IDE_MASS                        1013
#define IDC_BUT_SELECT_VERTEX           1014
#define IDC_BUT_MANIP_MOVE              1015
#define IDC_BUT_SWITCH_MESH             1015
#define IDC_BUT_MANIP_ROTATE            1016
#define IDC_BUT_SWITCH_POINTS           1016
#define IDC_BUT_MANIP_SCALE             1017
#define IDC_BUT_SWITCH_LIGHTS           1017
#define IDC_INPUT_1                     1017
#define IDC_INPUT_2                     1018
#define IDC_INPUT_3                     1019
#define IDC_BUT_SELECT_OBJECT           1020
#define IDC_INPUT_4                     1020
#define IDC_BUT_NEW_BLOCK               1021
#define IDC_INPUT_5                     1021
#define IDC_BUT_SELECT_MESH_POINT       1022
#define IDC_RADIO1                      1022
#define IDC_INPUT_6                     1022
#define IDR_IMPLICIT                    1022
#define IDC_BUT_SELECT_FACE             1023
#define IDC_RADIO2                      1023
#define IDR_EXPLICIT                    1023
#define IDC_BUT_SELECT_MESH             1024
#define IDC_BUTTON1                     1024
#define IDC_CREATE                      1024
#define IDC_UNSEL_NODE                  1024
#define IDC_ANIMATE_MODE                1024
#define IDC_COPY                        1025
#define IDC_SEL_ALL                     1025
#define IDC_BUT_GROW_SELECTED           1027
#define IDC_FIX                         1027
#define IDC_BUT_UNSELECT                1028
#define IDE_MODENUM                     1028
#define IDC_BUT_FIX                     1029
#define IDC_SPIN                        1029
#define IDC_BUT_CLEAR_IMPACTS           1030
#define IDE_EIGVAL                      1030
#define IDC_BUT_DELETE_MESH             1031
#define IDE_FX                          1031
#define IDE_NDOFS                       1031
#define IDC_BUT_TOGGLE_FACES            1032
#define IDE_FY                          1032
#define IDE_PERIOD                      1032
#define IDC_BUT_CLEAR_FIXITIES          1033
#define IDC_APPLY                       1033
#define IDC_BUT_DELETE_SELECTED         1034
#define IDC_BUT_SWITCH_ANIMATE          1034
#define IDC_DYNAMIC                     1034
#define IDE_DAMP                        1035
#define IDC_RESET                       1036
#define IDE_TIME                        1037
#define IDE_DT                          1039
#define IDE_FT                          1040
#define IDC_MASS                        1041
#define IDE_AREA                        1042
#define IDE_ELAST                       1043
#define IDC_MAT                         1044
#define IDC_BUT_ANIMATE_1               1046
#define IDC_BUT_ANIMATE_STOP_1          1047
#define IDC_BUT_ANIMATE_PAUSE           1048
#define IDC_EDIT_MODE_1                 1050
#define IDC_CHECK_LOOP                  1051
#define IDC_BUT_MOVE_LOADS              1053
#define IDC_BREAK_ANIMATE               1055
#define IDC_BREAK_NEW_BLOCK             1057
#define IDC_BREAK_SELECT                1058
#define IDC_BREAK_IMPACTS               1061
#define IDC_BREAK_FIX                   1062
#define IDC_BUT_PERSP                   1065
#define IDC_BUT_UNCREASE                1066
#define IDC_BUT_RESIZE_POINTS           1067
#define IDC_BUT_CREASE                  1068
#define IDC_BUT_CALC_NORMALS            1069
#define IDC_EDIT_CREASE                 1070
#define IDC_RAD_ALL_POINTS              1071
#define IDC_RAD_SELECTED_POINTS         1072
#define IDC_BREAK_CREASE_ANGLE          1073
#define IDC_BREAK_MANIP                 1074
#define IDC_BUT_REMOVE_POINTS           1075
#define IDC_BREAK_POINTS                1076
#define IDC_RAD_AMBIENT                 1078
#define IDC_RAD_DIFFUSE                 1079
#define IDC_RAD_EMISSIVE                1080
#define IDC_RAD_SPECULAR                1081
#define IDC_BREAK_COLOR                 1083
#define IDC_BUT_SWITCH_OBJECT           1085
#define IDC_RAD_RED                     1086
#define IDC_RAD_GREEN                   1087
#define IDC_RAD_BLUE                    1088
#define IDC_BUT_COLOR                   1091
#define IDC_BUT_DIRECTION               1092
#define IDC_BUT_POSITION                1093
#define IDC_RAD_RGB                     1094
#define IDC_BUT_SWITCH_SHAPE            1096
#define IDC_EDIT_STACKS                 1097
#define IDC_EDIT_SLICES                 1100
#define IDC_EDIT_RADIUS                 1101
#define IDC_BUT_CREATE_SPHERE           1102
#define IDC_BUT_UNSELECT_OBJECT         1104
#define IDC_BUT_DELETE_OBJECT           1105
#define IDC_BUT_SET_CENTER              1105
#define IDC_RAD_SHINE                   1106
#define IDC_BUT_TOGGLE_SURFACE          1107
#define IDC_BREAK_AXISYMM               1107
#define IDC_EDIT_RADIUS_2               1108
#define IDC_EDIT_HEIGHT_CONE            1109
#define IDC_BREAK_CUBE                  1110
#define IDC_EDIT_CUBE_SIZE_X            1111
#define IDC_BUT_CREATE_CONE             1112
#define IDC_BUT_CREATE_CYLINDER         1113
#define IDC_EDIT_CUBE_SIZE_Y            1114
#define IDC_EDIT_CUBE_SIZE_Z            1115
#define IDC_RAD_DIRECTIONAL             1116
#define IDC_EDIT_CUBE_SECTIONS_X        1116
#define IDC_RAD_POINT                   1117
#define IDC_EDIT_CUBE_SECTIONS_Y        1117
#define IDC_BREAK_EDIT                  1118
#define IDC_EDIT_CUBE_SECTIONS_Z        1118
#define IDC_BUT_NEW_LIGHT               1119
#define IDC_BUT_CREATE_CUBE             1119
#define IDC_BUT_CREATE_DONUT            1120
#define IDC_RAD_SHOW_LIGHTS             1121
#define IDC_RAD_HIDE_LIGHTS             1122
#define IDC_BUT_UNSELECT_LIGHTS         1123
#define IDC_BUT_SELECT_LIGHTS           1124
#define IDC_EDIT_BRICK_SIZE_X           1128
#define IDC_EDIT_BRICK_SIZE_Y           1129
#define ID_VIEW_X_Z_PLANE               32771
#define ID_PANEL_POINTS                 32771
#define ID_VIEW_X_Y_PLANE               32772
#define ID_PANEL_OBJECT                 32772
#define ID_PANEL_SHAPE                  32773
#define ID_PANEL_MESH                   32774
#define ID_VIEW_PERSP_BIAXI             32775
#define ID_PANEL_LIGHTS                 32775
#define ID_VIEW_BACKGROUND              32776
#define ID_VIEW_PERSP_TRACK             32777
#define ID_VIEW_ORTHO_BIAXI             32778
#define ID_VIEW_ORTHO_TRACK             32779
#define IDC_ANIMATE                     32784
#define ID_FILE_IMPORT                  32785
#define IDC_PAUSE                       32786
#define ID_QUAD_LAYOUT                  32787
#define IDC_STOP                        32788
#define ID_MONO_LAYOUT                  32789

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1045
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
